name: Continuous Publication

on:
  workflow_dispatch:
  push:
    branches:
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
    
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'
    
      - name: Install pnpm
        run: npm install -g pnpm@9.0.4
      
      - name: Install dependencies
        run: pnpm install
      
      - name: Run build
        run: pnpm run build
    
      - name: Prepare publication files
        run: |
          mkdir to_publish
          cp -r dist/* to_publish
          cp LICENSE to_publish
          cp .htaccess to_publish

      - name: Checkout master branch
        uses: actions/checkout@v4
        with:
          ref: master
          clean: false

      - name: Copy publication files to master branch
        run: cp -r to_publish/* .
      
      - name: Clean up publication files
        run: rm -rf to_publish

      - name: Commit and push to master branch
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m '[Automated] Publicate content'
          git push origin master