name: Continuous Publication

on:
  push:
    branches:
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: gh-pages
    
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'
    
      - name: Install dependencies
        run: npm ci
    
      - name: Run build
        run: npm run build
    
      - name: Push to master branch
        uses: EndBug/add-and-commit@v7
        with:
          author_name: 'GitHub Actions'
          author_email: 'actions@github.com'
          message: '[Automated] Update dist content'
          add: 'dist/* LICENSE.txt .htaccess'
          branch: 'master'
